In [9]:
import pandas as pd

# Notice the double .csv.csv at the very end!
df = pd.read_csv(r"E:\DataForge_Internship_DAKSHINI\DataForge_EDA_Sprint_2026_2026CS001\01_data\raw\dataset_raw.csv.csv")

# Display the first few rows to confirm it worked
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,? 261.96
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",? 731.94
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,? 14.62
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,? 957.58
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,? 22.37

In [10]:
# Display basics
display(df.head())
display(df.tail())

# Display info and memory usage
df.info(memory_usage="deep")
display(df.describe())
display(df.isnull().sum())

# Display specific shape and attributes
print("Exact Shape:", df.shape)
print("Columns:", df.columns)
print("Data Types:\n", df.dtypes)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,? 261.96
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",? 731.94
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,? 14.62
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,? 957.58
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,? 22.37

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21-05-2017,28-05-2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",? 3.80
9796,9797,CA-2016-128608,12-01-2016,17-01-2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",? 10.37
9797,9798,CA-2016-128608,12-01-2016,17-01-2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,? 235.19
9798,9799,CA-2016-128608,12-01-2016,17-01-2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,? 26.38
9799,9800,CA-2016-128608,12-01-2016,17-01-2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,? 10.38

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9790 non-null   str
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   str
dtypes: int64(1), str(17)
memory usage: 3.2 MB

            Row ID
count  9800.000000
mean   4900.500000
std    2829.160653
min       1.000000
25%    2450.750000
50%    4900.500000
75%    7350.250000
max    9800.000000

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      10
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

Exact Shape: (9800, 18)
Columns: Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')
Data Types:
 Row ID           int64
Order ID           str
Order Date         str
Ship Date          str
Ship Mode          str
Customer ID        str
Customer Name      str
Segment            str
Country            str
City               str
State              str
Postal Code        str
Region             str
Product ID         str
Category           str
Sub-Category       str
Product Name       str
Sales              str
dtype: object

In [11]:
schema = pd.DataFrame({
    "column": df.columns,
    "dtype": [str(df[c].dtype) for c in df.columns],
    "missing": [df[c].isna().sum() for c in df.columns],
    "unique": [df[c].nunique() for c in df.columns],
    "sample": [df[c].dropna().iloc[0] if df[c].dropna().shape[0] else "" for c in df.columns]
})
display(schema)

           column  dtype  missing  unique                             sample
0          Row ID  int64        0    9800                                  1
1        Order ID    str        0    4922                     CA-2017-152156
2      Order Date    str        0    1230                         08-11-2017
3       Ship Date    str        0    1326                         11-11-2017
4       Ship Mode    str        0       4                       Second Class
5     Customer ID    str        0     793                           CG-12520
6   Customer Name    str        0     793                        Claire Gute
7         Segment    str        0       3                           Consumer
8         Country    str        0       1                      United States
9            City    str        0     529                          Henderson
10          State    str        0      49                           Kentucky
11    Postal Code    str       10     627                              42420
12         Region    str        0       4                              South
13     Product ID    str        0    1861                    FUR-BO-10001798
14       Category    str        0       3                          Furniture
15   Sub-Category    str        0      17                          Bookcases
16   Product Name    str        0    1849  Bush Somerset Collection Bookcase
17          Sales    str        0    5396                           ? 261.96

In [17]:
import os

notebook_dir = r"E:\DataForge_Internship_DAKSHINI\DataForge_EDA_Sprint_2026_2026CS001\04_python\notebooks"

# Create data_info.txt
with open(rf"{notebook_dir}\data_info.txt", "w") as f:
    f.write(f"Exact Shape: {df.shape}\n")
    f.write(f"Memory Usage: {df.memory_usage(deep=True).sum()} bytes\n")
print("✅ data_info.txt created successfully!")

✅ data_info.txt created successfully!

In [18]:
notebook_dir = r"E:\DataForge_Internship_DAKSHINI\DataForge_EDA_Sprint_2026_2026CS001\04_python\notebooks"

with open(rf"{notebook_dir}\report_p7.md", "w") as f:
    f.write("# Practical 7: Pandas DataFrame Architecture\n")
    f.write("- Dataset loaded successfully.\n")
    f.write("- Inspection completed using vectorized data structures.\n")
    f.write("- Schema audit table created and exported.\n")
print("✅ report_p7.md created successfully!")

✅ report_p7.md created successfully!